### ISSUE TITLE
Documentation improvement request

### ISSUE THREAD

**Issue by woshishiq1** [stanislawrogasik/Pixel2XL-VoLTE-VoWiFi#1]
The tutorial is too general to understand! Just say step 6, put the file in the EfsTools folder. It is not clear whether this folder was created on the internal memory card of the mobile phone or the folder after the pc system EFS tool decompressed the package. Can you explain it in detail? Thank you

**Comment by stanislawrogasik** [comment]
Hi @woshishiq1,

I've updated the guide - please take a look and get back to me in case of any questions.
Possibly, I'll also drop a video tutorial in near future

**Comment by woshishiq1** [comment]
![7_~N`FZNR UO1}G@9OK%%0J](https://user-images.githubusercontent.com/90903172/168104088-692d08ca-5b9c-47f9-a02e-20e88f8547b7.png)
![P%728C~H{6HV$}LK`JPG}3B](https://user-images.githubusercontent.com/90903172/168104111-0fa796a0-6b0d-43df-a764-25b006b89762.png)
I installed everything that should be downloaded and installed step by step. What's wrong with this error report? worry

**Comment by woshishiq1** [comment]
![7_~N`FZNR UO1}G@9OK%%0J](https://user-images.githubusercontent.com/90903172/168104555-a5fd4059-8454-4715-945b-64bb39255791.png)

**Comment by stanislawrogasik** [comment]
> ![7_~N`FZNR UO1}G@9OK%%0J](https://user-images.githubusercontent.com/90903172/168104555-a5fd4059-8454-4715-945b-64bb39255791.png)

Try to launch commands one-by-one instead of pasting whole command.
You should see this:
```
taimen:/ # resetprop ro.bootmode usbradio
taimen:/ # resetprop ro.build.type userdebug
taimen:/ # resetprop sys.usb.configfs 1
```
and so on... So copy&paste those commands but **one-by-one**

**Comment by woshishiq1** [comment]
![8`SE5@@%5(7@VZVOH7RA96X](https://user-images.githubusercontent.com/90903172/168193924-2e2045b9-7c2b-4d9c-9518-b84237e417e4.png)

**Comment by woshishiq1** [comment]
![U0 KPU({CQ PM~DLM)NM6EL](https://user-images.githubusercontent.com/90903172/168193935-cd6e3122-a776-482f-b1d6-a1288ee024b9.png)

**Comment by woshishiq1** [comment]
Still can't, I can't do it well. Maybe I'm too stupid - -! My computer only displays COM1 port, and I can't connect to Android devices with Qost. Your project is a good project, but I can't do it well. I'd better use twrp to restore backup and Android 11. By the way, I tested the Los system. In addition, there is a problem with your pixel2xl volte VoWiFi / magickmodules! One more layer of folder should be the module file directly in the compressed package!
